export const USER_ACTION_TYPES = {
    FETCH_USERS_REQUEST:'user/FETCH_USERS_REQUEST',
    FETCH_USERS_SUCCESS:'user/FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE:'user/FETCH_USERS_FAILURE',
    ADD_USER:'user/ADD_USER',
    UPDATE_USER:'user/UPDATE_USER',
    DELETE_USER:'user/DELETE_USER'
}